name: Linux arm64 AppImage

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '*.md'
      - 'Documents/**'
  release:
    types: [published]
    paths-ignore:
      - '*.md'
      - 'Documents/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependency
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

      - name: Build QUASI88 Linux app
        run: |
          cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build -j 2
          cp build/quasi88 build/QUASI88_Linux_arm64.appimage

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: QUASI88_Linux_arm64.appimage
          path: build/QUASI88_Linux_arm64.appimage

      - name: Update Release
        if: ${{ github.event_name == 'release' && !env.ACT }}
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/QUASI88_Linux_arm64.appimage
          overwrite: true
