name: macOS Build

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '*.md'
      - 'doc/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'doc/**'
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download SDL2 Framework
        run: |
          curl -L -o SDL2.dmg https://github.com/libsdl-org/SDL/releases/download/release-2.32.8/SDL2-2.32.8.dmg
          hdiutil attach SDL2.dmg
          cp -R /Volumes/SDL2/SDL2.framework .
          hdiutil detach /Volumes/SDL2

      - name: Build QUASI88 macOS app
        run: |
          cmake -S. -Bbuild \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" \
            -DCMAKE_FRAMEWORK_PATH=$(pwd) \
            -DCMAKE_INSTALL_PREFIX=$(pwd)/dist \
            -DMACOSX_STANDALONE_APP_BUNDLE=ON \
            -DCPACK=ON
          cmake --build build --config Release
          cmake --install build

      - name: Package app
        run: |
          ditto -c -k --sequesterRsrc --keepParent \
            dist/QUASI88.app \
            QUASI88_macOS.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QUASI88_macOS
          path: QUASI88_macOS.zip

      - name: Update Release
        if: ${{ github.event_name == 'release' && !env.ACT }}
        uses: svenstaro/upload-release-action@v2
        with:
          file: QUASI88_macOS.zip
          overwrite: true
          tag: ${{ github.ref }}
