name: Raspberry Pi OS armhf Build

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '*.md'
      - 'doc/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'doc/**'
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Switch apt sources to ports.ubuntu.com for armhf
        run: |
          FLAVOR="$(lsb_release -sc)"
          sudo tee /etc/apt/sources.list.d/armhf.list <<LIST
          deb [arch=armhf] http://ports.ubuntu.com/ ${FLAVOR} main restricted
          deb [arch=armhf] http://ports.ubuntu.com/ ${FLAVOR}-updates main restricted
          deb [arch=armhf] http://ports.ubuntu.com/ ${FLAVOR} universe
          deb [arch=armhf] http://ports.ubuntu.com/ ${FLAVOR}-updates universe
          deb [arch=armhf] http://ports.ubuntu.com/ ${FLAVOR} multiverse
          deb [arch=armhf] http://ports.ubuntu.com/ ${FLAVOR}-updates multiverse
          deb [arch=armhf] http://ports.ubuntu.com/ ${FLAVOR}-backports main restricted universe multiverse
          LIST
          sudo sed -E -i 's/deb (http|file|mirror)/deb [arch=amd64,i386] \1/' /etc/apt/sources.list

      - name: Install cross compile tools
        run: |
          sudo dpkg --add-architecture armhf
          sudo apt-get update
          sudo apt-get install -y cmake pkg-config libsdl2-dev:armhf g++-arm-linux-gnueabihf

      - name: Configure and build
        run: |
          export PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig
          cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCPACK=ON -DCMAKE_INSTALL_PREFIX=/usr \
            -DCMAKE_C_COMPILER=arm-linux-gnueabihf-gcc \
            -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ \
            -DCPACK_GENERATOR=DEB \
            -DCPACK_DEBIAN_PACKAGE_ARCHITECTURE=armhf
          cmake --build build -j $(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QUASI88_Linux_armhf
          path: build/quasi88

      - name: Package for Release
        if: ${{ github.event_name == 'release' && !env.ACT }}
        run: |
          cd build
          cpack -G DEB
          mv *.deb QUASI88_Linux_armhf.deb

      - name: Update Release
        if: ${{ github.event_name == 'release' && !env.ACT }}
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/QUASI88_Linux_armhf.deb
          overwrite: true
          tag: ${{ github.ref_name }}
